[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*/custom/themes"]
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".pyenv"]
    type = "archive"
    url = "https://github.com/pyenv/pyenv/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/colors/onedark.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/joshdick/onedark.vim/refs/heads/main/colors/onedark.vim"
    refreshPeriod = "168h"
[".vim/autoload/onedark.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/joshdick/onedark.vim/refs/heads/main/autoload/onedark.vim"
    refreshPeriod = "168h"

