[language-server.ruff]
command = "ruff"
args = ["server", "-q", "--preview"]

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json", "requirements.txt", ".venv/"]
comment-token = "#"
language-servers = [ {name = "pyright", except-features=["diagnostics"]}, "ruff" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter =  { command = "ruff", args = ["format", "-"] }
